- name: Job Pipeline Scheduler
  env:
    AI_BACKEND: groq
    AI_API_KEY: ${{ secrets.AI_API_KEY }}
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    GOOGLE_CREDENTIALS_FILE: credentials.json
    GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
    GOOGLE_AUTH_METHOD: service_account

    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  run: python main.py